name: mmoSkills
main: mmo.Skills.MMOSkills
version: 0.1
website: http://forums.bukkit.org/threads/
author: Olloth <olloth@gmail.com>
depend: [Spout,mmoCore]

description: Utility functions for mmo-minecraft
