name: mmoSkills
version: ${releaseVersion}.${buildNumber}
description: Gives an event based API for skill use.
author: mmoMinecraftDev
website: http://mmo.me.uk

main: mmo.Skills.MMOSkills
depend: [Spout, mmoCore]
